export const resultMockAPI = [
	{
		adult: false,
		backdrop_path: "/jMWkd0fuwbG39eJpzycJzPWMCww.jpg",
		genre_ids: [28, 878],
		id: 399566,
		original_language: "en",
		original_title: "Godzilla vs. Kong",
		overview:
			"In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
		popularity: 12276.164,
		poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
		release_date: "2021-03-24",
		title: "Godzilla vs. Kong",
		video: false,
		vote_average: 8.5,
		vote_count: 3719,
	},
	{
		adult: false,
		backdrop_path: "/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg",
		genre_ids: [16, 12, 14, 10751, 28],
		id: 527774,
		original_language: "en",
		original_title: "Raya and the Last Dragon",
		overview:
			"Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
		popularity: 2495.914,
		poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
		release_date: "2021-03-03",
		title: "Raya and the Last Dragon",
		video: false,
		vote_average: 8.3,
		vote_count: 2088,
	},
	{
		adult: false,
		backdrop_path: "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
		genre_ids: [35, 10751, 16],
		id: 587807,
		original_language: "en",
		original_title: "Tom & Jerry",
		overview:
			"Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
		popularity: 1689.341,
		poster_path: "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
		release_date: "2021-02-11",
		title: "Tom & Jerry",
		video: false,
		vote_average: 7.4,
		vote_count: 1130,
	},
];
